name: kidnap_detection_app
description: kidnap detector app.

publish_to: "none"

version: 0.0.101+101

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  dio: ^4.0.6
  flutter_modular: ^5.0.3
  mobx: ^2.1.4
  video_player: ^2.2.5
  flutter_mobx: ^2.0.6+5
  export_video_frame: ^0.0.7
  socket_io_client: ^2.0.2
  flutter_screenutil:
  provider:

dev_dependencies:
  build_runner:
  flutter_gen_runner:


  dart_code_metrics: ^5.3.0
  lints: ^2.0.1

  mobx_codegen: ^2.1.1

flutter_gen:
  output: lib/core/gen

  integrations:
    flutter_svg: true
    lottie: true


flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/fonts/
    - assets/videos/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal.ttf
